name: Release

on:
#  TODO: Review with the team a time proposal to schedule a release
#  schedule:
#    # 2 AM on Sunday
#    - cron: "0 2 * * 0"
  workflow_dispatch:
    inputs:
      nexus_package:
        description: Publish to Nexus Packages
        required: false
        default: '0'
      github_package:
        description: Publish to GitHub Packages
        required: false
        default: '0'
      github_nexus_package:
        description: Publish to GitHub & Nexus Packages
        required: false
        default: '0'

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: run semantic-release
        run: ./ci/release/run.sh
        id: semanticrelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      new-release-version: ${{ steps.semanticrelease.outputs.new-release-version }}
